Using pip 24.2 from /home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip (python 3.12)
Obtaining file:///home/rladmin/cchia/cuda-python
ERROR: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Using pip 24.2 from /home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip (python 3.12)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-build-tracker-qth94yn7
Initialized build tracking at /tmp/pip-build-tracker-qth94yn7
Created build tracker: /tmp/pip-build-tracker-qth94yn7
Entered build tracker: /tmp/pip-build-tracker-qth94yn7
Created temporary directory: /tmp/pip-install-dk00gose
Created temporary directory: /tmp/pip-ephem-wheel-cache-3o8mphch
Obtaining file:///home/rladmin/cchia/cuda-python
  Added file:///home/rladmin/cchia/cuda-python to build tracker '/tmp/pip-build-tracker-qth94yn7'
Remote version of pip: 25.2
Local version of pip:  24.2
Was pip installed by pip? False
ERROR: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Exception information:
Traceback (most recent call last):
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 539, in collect_root_requirements
    reqs = list(
           ^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 495, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_base_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
                                           ^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 328, in __init__
    super().__init__(
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 338, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 698, in prepare_editable_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 39, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 512, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/asloboda/miniconda3/lib/python3.12/site-packages/pip/_internal/pyproject.py", line 63, in load_pyproject_toml
    raise InstallationError(
pip._internal.exceptions.InstallationError: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Removed file:///home/rladmin/cchia/cuda-python from build tracker '/tmp/pip-build-tracker-qth94yn7'
Removed build tracker: '/tmp/pip-build-tracker-qth94yn7'
Using pip 24.0 from /home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip (python 3.12)
Obtaining file:///home/rladmin/cchia/cuda-python
ERROR: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: pip install --upgrade pip
Using pip 24.0 from /home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip (python 3.12)
Obtaining file:///home/rladmin/cchia/cuda-python
ERROR: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: pip install --upgrade pip
Using pip 24.0 from /home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip (python 3.12)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-build-tracker-vw4kxlpk
Initialized build tracking at /tmp/pip-build-tracker-vw4kxlpk
Created build tracker: /tmp/pip-build-tracker-vw4kxlpk
Entered build tracker: /tmp/pip-build-tracker-vw4kxlpk
Created temporary directory: /tmp/pip-install-42lqq_c_
Created temporary directory: /tmp/pip-ephem-wheel-cache-mlbiag37
Obtaining file:///home/rladmin/cchia/cuda-python
  Added file:///home/rladmin/cchia/cuda-python to build tracker '/tmp/pip-build-tracker-vw4kxlpk'
ERROR: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Exception information:
Traceback (most recent call last):
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
    reqs = list(
           ^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 207, in _make_base_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
                                           ^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 315, in __init__
    super().__init__(
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 325, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 696, in prepare_editable_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 37, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 516, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/pyproject.py", line 57, in load_pyproject_toml
    raise InstallationError(
pip._internal.exceptions.InstallationError: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Remote version of pip: 25.2
Local version of pip:  24.0
Was pip installed by pip? True

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: pip install --upgrade pip
Removed file:///home/rladmin/cchia/cuda-python from build tracker '/tmp/pip-build-tracker-vw4kxlpk'
Removed build tracker: '/tmp/pip-build-tracker-vw4kxlpk'
Using pip 24.0 from /home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip (python 3.12)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-build-tracker-3vzkkc0v
Initialized build tracking at /tmp/pip-build-tracker-3vzkkc0v
Created build tracker: /tmp/pip-build-tracker-3vzkkc0v
Entered build tracker: /tmp/pip-build-tracker-3vzkkc0v
Created temporary directory: /tmp/pip-install-zn6wmm_r
Created temporary directory: /tmp/pip-ephem-wheel-cache-1n8smixk
Obtaining file:///home/rladmin/cchia/cuda-python
  Added file:///home/rladmin/cchia/cuda-python to build tracker '/tmp/pip-build-tracker-3vzkkc0v'
ERROR: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Exception information:
Traceback (most recent call last):
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
    reqs = list(
           ^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 207, in _make_base_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
                                           ^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 315, in __init__
    super().__init__(
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 325, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 696, in prepare_editable_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 37, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 516, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/rladmin/cchia/cuda-python/venvs/cuda_python/lib/python3.12/site-packages/pip/_internal/pyproject.py", line 57, in load_pyproject_toml
    raise InstallationError(
pip._internal.exceptions.InstallationError: file:///home/rladmin/cchia/cuda-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Remote version of pip: 25.2
Local version of pip:  24.0
Was pip installed by pip? True

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: pip install --upgrade pip
Removed file:///home/rladmin/cchia/cuda-python from build tracker '/tmp/pip-build-tracker-3vzkkc0v'
Removed build tracker: '/tmp/pip-build-tracker-3vzkkc0v'
